/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the articolo table.
 */
public class ArticoloPk implements Serializable
{
	protected long artId;

	/** 
	 * This attribute represents whether the primitive attribute artId is null.
	 */
	protected boolean artIdNull;

	/** 
	 * Sets the value of artId
	 */
	public void setArtId(long artId)
	{
		this.artId = artId;
	}

	/** 
	 * Gets the value of artId
	 */
	public long getArtId()
	{
		return artId;
	}

	/**
	 * Method 'ArticoloPk'
	 * 
	 */
	public ArticoloPk()
	{
	}

	/**
	 * Method 'ArticoloPk'
	 * 
	 * @param artId
	 */
	public ArticoloPk(final long artId)
	{
		this.artId = artId;
	}

	/** 
	 * Sets the value of artIdNull
	 */
	public void setArtIdNull(boolean artIdNull)
	{
		this.artIdNull = artIdNull;
	}

	/** 
	 * Gets the value of artIdNull
	 */
	public boolean isArtIdNull()
	{
		return artIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ArticoloPk)) {
			return false;
		}
		
		final ArticoloPk _cast = (ArticoloPk) _other;
		if (artId != _cast.artId) {
			return false;
		}
		
		if (artIdNull != _cast.artIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (artId ^ (artId >>> 32));
		_hashCode = 29 * _hashCode + (artIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.ArticoloPk: " );
		ret.append( "artId=" + artId );
		return ret.toString();
	}

}
