/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import com.inn.logistica.dao.*;
import com.inn.logistica.factory.*;
import com.inn.logistica.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Corrieri implements Serializable
{
	/** 
	 * This attribute maps to the column cor_id in the corrieri table.
	 */
	protected long corId;

	/** 
	 * This attribute maps to the column cor_nominativo in the corrieri table.
	 */
	protected String corNominativo;

	/** 
	 * This attribute maps to the column cor_url_tracking in the corrieri table.
	 */
	protected String corUrlTracking;

	/** 
	 * This attribute maps to the column cor_abil_tracking in the corrieri table.
	 */
	protected int corAbilTracking;

	/**
	 * Method 'Corrieri'
	 * 
	 */
	public Corrieri()
	{
	}

	/**
	 * Method 'getCorId'
	 * 
	 * @return long
	 */
	public long getCorId()
	{
		return corId;
	}

	/**
	 * Method 'setCorId'
	 * 
	 * @param corId
	 */
	public void setCorId(long corId)
	{
		this.corId = corId;
	}

	/**
	 * Method 'getCorNominativo'
	 * 
	 * @return String
	 */
	public String getCorNominativo()
	{
		return corNominativo;
	}

	/**
	 * Method 'setCorNominativo'
	 * 
	 * @param corNominativo
	 */
	public void setCorNominativo(String corNominativo)
	{
		this.corNominativo = corNominativo;
	}

	/**
	 * Method 'getCorUrlTracking'
	 * 
	 * @return String
	 */
	public String getCorUrlTracking()
	{
		return corUrlTracking;
	}

	/**
	 * Method 'setCorUrlTracking'
	 * 
	 * @param corUrlTracking
	 */
	public void setCorUrlTracking(String corUrlTracking)
	{
		this.corUrlTracking = corUrlTracking;
	}

	/**
	 * Method 'getCorAbilTracking'
	 * 
	 * @return int
	 */
	public int getCorAbilTracking()
	{
		return corAbilTracking;
	}

	/**
	 * Method 'setCorAbilTracking'
	 * 
	 * @param corAbilTracking
	 */
	public void setCorAbilTracking(int corAbilTracking)
	{
		this.corAbilTracking = corAbilTracking;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Corrieri)) {
			return false;
		}
		
		final Corrieri _cast = (Corrieri) _other;
		if (corId != _cast.corId) {
			return false;
		}
		
		if (corNominativo == null ? _cast.corNominativo != corNominativo : !corNominativo.equals( _cast.corNominativo )) {
			return false;
		}
		
		if (corUrlTracking == null ? _cast.corUrlTracking != corUrlTracking : !corUrlTracking.equals( _cast.corUrlTracking )) {
			return false;
		}
		
		if (corAbilTracking != _cast.corAbilTracking) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (corId ^ (corId >>> 32));
		if (corNominativo != null) {
			_hashCode = 29 * _hashCode + corNominativo.hashCode();
		}
		
		if (corUrlTracking != null) {
			_hashCode = 29 * _hashCode + corUrlTracking.hashCode();
		}
		
		_hashCode = 29 * _hashCode + corAbilTracking;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CorrieriPk
	 */
	public CorrieriPk createPk()
	{
		return new CorrieriPk(corId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.Corrieri: " );
		ret.append( "corId=" + corId );
		ret.append( ", corNominativo=" + corNominativo );
		ret.append( ", corUrlTracking=" + corUrlTracking );
		ret.append( ", corAbilTracking=" + corAbilTracking );
		return ret.toString();
	}

}
