/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import com.inn.logistica.dao.*;
import com.inn.logistica.factory.*;
import com.inn.logistica.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class MovimentazioniArticoli implements Serializable
{
	/** 
	 * This attribute maps to the column mvd_id in the movimentazioni_articoli table.
	 */
	protected long mvdId;

	/** 
	 * This attribute maps to the column mvd_qta in the movimentazioni_articoli table.
	 */
	protected int mvdQta;

	/** 
	 * This attribute maps to the column articolo_art_id in the movimentazioni_articoli table.
	 */
	protected long articoloArtId;

	/** 
	 * This attribute maps to the column movimentazioni_mov_id in the movimentazioni_articoli table.
	 */
	protected long movimentazioniMovId;

	/**
	 * Method 'MovimentazioniArticoli'
	 * 
	 */
	public MovimentazioniArticoli()
	{
	}

	/**
	 * Method 'getMvdId'
	 * 
	 * @return long
	 */
	public long getMvdId()
	{
		return mvdId;
	}

	/**
	 * Method 'setMvdId'
	 * 
	 * @param mvdId
	 */
	public void setMvdId(long mvdId)
	{
		this.mvdId = mvdId;
	}

	/**
	 * Method 'getMvdQta'
	 * 
	 * @return int
	 */
	public int getMvdQta()
	{
		return mvdQta;
	}

	/**
	 * Method 'setMvdQta'
	 * 
	 * @param mvdQta
	 */
	public void setMvdQta(int mvdQta)
	{
		this.mvdQta = mvdQta;
	}

	/**
	 * Method 'getArticoloArtId'
	 * 
	 * @return long
	 */
	public long getArticoloArtId()
	{
		return articoloArtId;
	}

	/**
	 * Method 'setArticoloArtId'
	 * 
	 * @param articoloArtId
	 */
	public void setArticoloArtId(long articoloArtId)
	{
		this.articoloArtId = articoloArtId;
	}

	/**
	 * Method 'getMovimentazioniMovId'
	 * 
	 * @return long
	 */
	public long getMovimentazioniMovId()
	{
		return movimentazioniMovId;
	}

	/**
	 * Method 'setMovimentazioniMovId'
	 * 
	 * @param movimentazioniMovId
	 */
	public void setMovimentazioniMovId(long movimentazioniMovId)
	{
		this.movimentazioniMovId = movimentazioniMovId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MovimentazioniArticoli)) {
			return false;
		}
		
		final MovimentazioniArticoli _cast = (MovimentazioniArticoli) _other;
		if (mvdId != _cast.mvdId) {
			return false;
		}
		
		if (mvdQta != _cast.mvdQta) {
			return false;
		}
		
		if (articoloArtId != _cast.articoloArtId) {
			return false;
		}
		
		if (movimentazioniMovId != _cast.movimentazioniMovId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (mvdId ^ (mvdId >>> 32));
		_hashCode = 29 * _hashCode + mvdQta;
		_hashCode = 29 * _hashCode + (int) (articoloArtId ^ (articoloArtId >>> 32));
		_hashCode = 29 * _hashCode + (int) (movimentazioniMovId ^ (movimentazioniMovId >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MovimentazioniArticoliPk
	 */
	public MovimentazioniArticoliPk createPk()
	{
		return new MovimentazioniArticoliPk(mvdId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.MovimentazioniArticoli: " );
		ret.append( "mvdId=" + mvdId );
		ret.append( ", mvdQta=" + mvdQta );
		ret.append( ", articoloArtId=" + articoloArtId );
		ret.append( ", movimentazioniMovId=" + movimentazioniMovId );
		return ret.toString();
	}

}
