/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the ordini_articoli table.
 */
public class OrdiniArticoliPk implements Serializable
{
	protected long odeId;

	/** 
	 * This attribute represents whether the primitive attribute odeId is null.
	 */
	protected boolean odeIdNull;

	/** 
	 * Sets the value of odeId
	 */
	public void setOdeId(long odeId)
	{
		this.odeId = odeId;
	}

	/** 
	 * Gets the value of odeId
	 */
	public long getOdeId()
	{
		return odeId;
	}

	/**
	 * Method 'OrdiniArticoliPk'
	 * 
	 */
	public OrdiniArticoliPk()
	{
	}

	/**
	 * Method 'OrdiniArticoliPk'
	 * 
	 * @param odeId
	 */
	public OrdiniArticoliPk(final long odeId)
	{
		this.odeId = odeId;
	}

	/** 
	 * Sets the value of odeIdNull
	 */
	public void setOdeIdNull(boolean odeIdNull)
	{
		this.odeIdNull = odeIdNull;
	}

	/** 
	 * Gets the value of odeIdNull
	 */
	public boolean isOdeIdNull()
	{
		return odeIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof OrdiniArticoliPk)) {
			return false;
		}
		
		final OrdiniArticoliPk _cast = (OrdiniArticoliPk) _other;
		if (odeId != _cast.odeId) {
			return false;
		}
		
		if (odeIdNull != _cast.odeIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (odeId ^ (odeId >>> 32));
		_hashCode = 29 * _hashCode + (odeIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.OrdiniArticoliPk: " );
		ret.append( "odeId=" + odeId );
		return ret.toString();
	}

}
