/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import com.inn.logistica.dao.*;
import com.inn.logistica.factory.*;
import com.inn.logistica.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class OrdiniArticoli implements Serializable
{
	/** 
	 * This attribute maps to the column ode_id in the ordini_articoli table.
	 */
	protected long odeId;

	/** 
	 * This attribute maps to the column ode_qta in the ordini_articoli table.
	 */
	protected int odeQta;

	/** 
	 * This attribute maps to the column ordini_ord_id in the ordini_articoli table.
	 */
	protected long ordiniOrdId;

	/** 
	 * This attribute maps to the column articolo_art_id in the ordini_articoli table.
	 */
	protected long articoloArtId;

	/**
	 * Method 'OrdiniArticoli'
	 * 
	 */
	public OrdiniArticoli()
	{
	}

	/**
	 * Method 'getOdeId'
	 * 
	 * @return long
	 */
	public long getOdeId()
	{
		return odeId;
	}

	/**
	 * Method 'setOdeId'
	 * 
	 * @param odeId
	 */
	public void setOdeId(long odeId)
	{
		this.odeId = odeId;
	}

	/**
	 * Method 'getOdeQta'
	 * 
	 * @return int
	 */
	public int getOdeQta()
	{
		return odeQta;
	}

	/**
	 * Method 'setOdeQta'
	 * 
	 * @param odeQta
	 */
	public void setOdeQta(int odeQta)
	{
		this.odeQta = odeQta;
	}

	/**
	 * Method 'getOrdiniOrdId'
	 * 
	 * @return long
	 */
	public long getOrdiniOrdId()
	{
		return ordiniOrdId;
	}

	/**
	 * Method 'setOrdiniOrdId'
	 * 
	 * @param ordiniOrdId
	 */
	public void setOrdiniOrdId(long ordiniOrdId)
	{
		this.ordiniOrdId = ordiniOrdId;
	}

	/**
	 * Method 'getArticoloArtId'
	 * 
	 * @return long
	 */
	public long getArticoloArtId()
	{
		return articoloArtId;
	}

	/**
	 * Method 'setArticoloArtId'
	 * 
	 * @param articoloArtId
	 */
	public void setArticoloArtId(long articoloArtId)
	{
		this.articoloArtId = articoloArtId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof OrdiniArticoli)) {
			return false;
		}
		
		final OrdiniArticoli _cast = (OrdiniArticoli) _other;
		if (odeId != _cast.odeId) {
			return false;
		}
		
		if (odeQta != _cast.odeQta) {
			return false;
		}
		
		if (ordiniOrdId != _cast.ordiniOrdId) {
			return false;
		}
		
		if (articoloArtId != _cast.articoloArtId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (odeId ^ (odeId >>> 32));
		_hashCode = 29 * _hashCode + odeQta;
		_hashCode = 29 * _hashCode + (int) (ordiniOrdId ^ (ordiniOrdId >>> 32));
		_hashCode = 29 * _hashCode + (int) (articoloArtId ^ (articoloArtId >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return OrdiniArticoliPk
	 */
	public OrdiniArticoliPk createPk()
	{
		return new OrdiniArticoliPk(odeId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.OrdiniArticoli: " );
		ret.append( "odeId=" + odeId );
		ret.append( ", odeQta=" + odeQta );
		ret.append( ", ordiniOrdId=" + ordiniOrdId );
		ret.append( ", articoloArtId=" + articoloArtId );
		return ret.toString();
	}

}
