/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.jdbc;

import com.inn.logistica.dao.*;
import com.inn.logistica.factory.*;
import java.util.Date;
import com.inn.logistica.dto.*;
import com.inn.logistica.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class AnagraficaDaoImpl extends AbstractDAO implements AnagraficaDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ana_id, ana_ragione_sociale, ana_tipologia, ana_agg_dt, ana_cf_piva FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ana_id, ana_ragione_sociale, ana_tipologia, ana_agg_dt, ana_cf_piva ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ana_id = ?, ana_ragione_sociale = ?, ana_tipologia = ?, ana_agg_dt = ?, ana_cf_piva = ? WHERE ana_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ana_id = ?";

	/** 
	 * Index of column ana_id
	 */
	protected static final int COLUMN_ANA_ID = 1;

	/** 
	 * Index of column ana_ragione_sociale
	 */
	protected static final int COLUMN_ANA_RAGIONE_SOCIALE = 2;

	/** 
	 * Index of column ana_tipologia
	 */
	protected static final int COLUMN_ANA_TIPOLOGIA = 3;

	/** 
	 * Index of column ana_agg_dt
	 */
	protected static final int COLUMN_ANA_AGG_DT = 4;

	/** 
	 * Index of column ana_cf_piva
	 */
	protected static final int COLUMN_ANA_CF_PIVA = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column ana_id
	 */
	protected static final int PK_COLUMN_ANA_ID = 1;

	/** 
	 * Inserts a new row in the anagrafica table.
	 */
	public AnagraficaPk insert(Anagrafica dto) throws AnagraficaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setLong( index++, dto.getAnaId() );
			stmt.setString( index++, dto.getAnaRagioneSociale() );
			stmt.setString( index++, dto.getAnaTipologia() );
			stmt.setDate(index++, dto.getAnaAggDt()==null ? null : new java.sql.Date( dto.getAnaAggDt().getTime() ) );
			stmt.setString( index++, dto.getAnaCfPiva() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AnagraficaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the anagrafica table.
	 */
	public void update(AnagraficaPk pk, Anagrafica dto) throws AnagraficaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setLong( index++, dto.getAnaId() );
			stmt.setString( index++, dto.getAnaRagioneSociale() );
			stmt.setString( index++, dto.getAnaTipologia() );
			stmt.setDate(index++, dto.getAnaAggDt()==null ? null : new java.sql.Date( dto.getAnaAggDt().getTime() ) );
			stmt.setString( index++, dto.getAnaCfPiva() );
			stmt.setLong( 6, pk.getAnaId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AnagraficaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the anagrafica table.
	 */
	public void delete(AnagraficaPk pk) throws AnagraficaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setLong( 1, pk.getAnaId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AnagraficaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the anagrafica table that matches the specified primary-key value.
	 */
	public Anagrafica findByPrimaryKey(AnagraficaPk pk) throws AnagraficaDaoException
	{
		return findByPrimaryKey( pk.getAnaId() );
	}

	/** 
	 * Returns all rows from the anagrafica table that match the criteria 'ana_id = :anaId'.
	 */
	public Anagrafica findByPrimaryKey(long anaId) throws AnagraficaDaoException
	{
		Anagrafica ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ana_id = ?", new Object[] {  new Long(anaId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the anagrafica table that match the criteria ''.
	 */
	public Anagrafica[] findAll() throws AnagraficaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ana_id", null );
	}

	/** 
	 * Returns all rows from the anagrafica table that match the criteria 'ana_id = :anaId'.
	 */
	public Anagrafica[] findWhereAnaIdEquals(long anaId) throws AnagraficaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ana_id = ? ORDER BY ana_id", new Object[] {  new Long(anaId) } );
	}

	/** 
	 * Returns all rows from the anagrafica table that match the criteria 'ana_ragione_sociale = :anaRagioneSociale'.
	 */
	public Anagrafica[] findWhereAnaRagioneSocialeEquals(String anaRagioneSociale) throws AnagraficaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ana_ragione_sociale = ? ORDER BY ana_ragione_sociale", new Object[] { anaRagioneSociale } );
	}

	/** 
	 * Returns all rows from the anagrafica table that match the criteria 'ana_tipologia = :anaTipologia'.
	 */
	public Anagrafica[] findWhereAnaTipologiaEquals(String anaTipologia) throws AnagraficaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ana_tipologia = ? ORDER BY ana_tipologia", new Object[] { anaTipologia } );
	}

	/** 
	 * Returns all rows from the anagrafica table that match the criteria 'ana_agg_dt = :anaAggDt'.
	 */
	public Anagrafica[] findWhereAnaAggDtEquals(Date anaAggDt) throws AnagraficaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ana_agg_dt = ? ORDER BY ana_agg_dt", new Object[] { anaAggDt==null ? null : new java.sql.Date( anaAggDt.getTime() ) } );
	}

	/** 
	 * Returns all rows from the anagrafica table that match the criteria 'ana_cf_piva = :anaCfPiva'.
	 */
	public Anagrafica[] findWhereAnaCfPivaEquals(String anaCfPiva) throws AnagraficaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ana_cf_piva = ? ORDER BY ana_cf_piva", new Object[] { anaCfPiva } );
	}

	/**
	 * Method 'AnagraficaDaoImpl'
	 * 
	 */
	public AnagraficaDaoImpl()
	{
	}

	/**
	 * Method 'AnagraficaDaoImpl'
	 * 
	 * @param userConn
	 */
	public AnagraficaDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "anagrafica";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Anagrafica fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Anagrafica dto = new Anagrafica();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Anagrafica[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Anagrafica dto = new Anagrafica();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Anagrafica ret[] = new Anagrafica[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Anagrafica dto, ResultSet rs) throws SQLException
	{
		dto.setAnaId( rs.getLong( COLUMN_ANA_ID ) );
		dto.setAnaRagioneSociale( rs.getString( COLUMN_ANA_RAGIONE_SOCIALE ) );
		dto.setAnaTipologia( rs.getString( COLUMN_ANA_TIPOLOGIA ) );
		dto.setAnaAggDt( rs.getDate(COLUMN_ANA_AGG_DT ) );
		dto.setAnaCfPiva( rs.getString( COLUMN_ANA_CF_PIVA ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Anagrafica dto)
	{
	}

	/** 
	 * Returns all rows from the anagrafica table that match the specified arbitrary SQL statement
	 */
	public Anagrafica[] findByDynamicSelect(String sql, Object[] sqlParams) throws AnagraficaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AnagraficaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the anagrafica table that match the specified arbitrary SQL statement
	 */
	public Anagrafica[] findByDynamicWhere(String sql, Object[] sqlParams) throws AnagraficaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AnagraficaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
