/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the anagrafica table.
 */
public class AnagraficaPk implements Serializable
{
	protected long anaId;

	/** 
	 * This attribute represents whether the primitive attribute anaId is null.
	 */
	protected boolean anaIdNull;

	/** 
	 * Sets the value of anaId
	 */
	public void setAnaId(long anaId)
	{
		this.anaId = anaId;
	}

	/** 
	 * Gets the value of anaId
	 */
	public long getAnaId()
	{
		return anaId;
	}

	/**
	 * Method 'AnagraficaPk'
	 * 
	 */
	public AnagraficaPk()
	{
	}

	/**
	 * Method 'AnagraficaPk'
	 * 
	 * @param anaId
	 */
	public AnagraficaPk(final long anaId)
	{
		this.anaId = anaId;
	}

	/** 
	 * Sets the value of anaIdNull
	 */
	public void setAnaIdNull(boolean anaIdNull)
	{
		this.anaIdNull = anaIdNull;
	}

	/** 
	 * Gets the value of anaIdNull
	 */
	public boolean isAnaIdNull()
	{
		return anaIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof AnagraficaPk)) {
			return false;
		}
		
		final AnagraficaPk _cast = (AnagraficaPk) _other;
		if (anaId != _cast.anaId) {
			return false;
		}
		
		if (anaIdNull != _cast.anaIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (anaId ^ (anaId >>> 32));
		_hashCode = 29 * _hashCode + (anaIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.AnagraficaPk: " );
		ret.append( "anaId=" + anaId );
		return ret.toString();
	}

}
