/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import com.inn.logistica.dao.*;
import com.inn.logistica.factory.*;
import com.inn.logistica.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Anagrafica implements Serializable
{
	/** 
	 * This attribute maps to the column ana_id in the anagrafica table.
	 */
	protected long anaId;

	/** 
	 * This attribute maps to the column ana_ragione_sociale in the anagrafica table.
	 */
	protected String anaRagioneSociale;

	/** 
	 * This attribute maps to the column ana_tipologia in the anagrafica table.
	 */
	protected String anaTipologia;

	/** 
	 * This attribute maps to the column ana_agg_dt in the anagrafica table.
	 */
	protected Date anaAggDt;

	/** 
	 * This attribute maps to the column ana_cf_piva in the anagrafica table.
	 */
	protected String anaCfPiva;

	/**
	 * Method 'Anagrafica'
	 * 
	 */
	public Anagrafica()
	{
	}

	/**
	 * Method 'getAnaId'
	 * 
	 * @return long
	 */
	public long getAnaId()
	{
		return anaId;
	}

	/**
	 * Method 'setAnaId'
	 * 
	 * @param anaId
	 */
	public void setAnaId(long anaId)
	{
		this.anaId = anaId;
	}

	/**
	 * Method 'getAnaRagioneSociale'
	 * 
	 * @return String
	 */
	public String getAnaRagioneSociale()
	{
		return anaRagioneSociale;
	}

	/**
	 * Method 'setAnaRagioneSociale'
	 * 
	 * @param anaRagioneSociale
	 */
	public void setAnaRagioneSociale(String anaRagioneSociale)
	{
		this.anaRagioneSociale = anaRagioneSociale;
	}

	/**
	 * Method 'getAnaTipologia'
	 * 
	 * @return String
	 */
	public String getAnaTipologia()
	{
		return anaTipologia;
	}

	/**
	 * Method 'setAnaTipologia'
	 * 
	 * @param anaTipologia
	 */
	public void setAnaTipologia(String anaTipologia)
	{
		this.anaTipologia = anaTipologia;
	}

	/**
	 * Method 'getAnaAggDt'
	 * 
	 * @return Date
	 */
	public Date getAnaAggDt()
	{
		return anaAggDt;
	}

	/**
	 * Method 'setAnaAggDt'
	 * 
	 * @param anaAggDt
	 */
	public void setAnaAggDt(Date anaAggDt)
	{
		this.anaAggDt = anaAggDt;
	}

	/**
	 * Method 'getAnaCfPiva'
	 * 
	 * @return String
	 */
	public String getAnaCfPiva()
	{
		return anaCfPiva;
	}

	/**
	 * Method 'setAnaCfPiva'
	 * 
	 * @param anaCfPiva
	 */
	public void setAnaCfPiva(String anaCfPiva)
	{
		this.anaCfPiva = anaCfPiva;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Anagrafica)) {
			return false;
		}
		
		final Anagrafica _cast = (Anagrafica) _other;
		if (anaId != _cast.anaId) {
			return false;
		}
		
		if (anaRagioneSociale == null ? _cast.anaRagioneSociale != anaRagioneSociale : !anaRagioneSociale.equals( _cast.anaRagioneSociale )) {
			return false;
		}
		
		if (anaTipologia == null ? _cast.anaTipologia != anaTipologia : !anaTipologia.equals( _cast.anaTipologia )) {
			return false;
		}
		
		if (anaAggDt == null ? _cast.anaAggDt != anaAggDt : !anaAggDt.equals( _cast.anaAggDt )) {
			return false;
		}
		
		if (anaCfPiva == null ? _cast.anaCfPiva != anaCfPiva : !anaCfPiva.equals( _cast.anaCfPiva )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (anaId ^ (anaId >>> 32));
		if (anaRagioneSociale != null) {
			_hashCode = 29 * _hashCode + anaRagioneSociale.hashCode();
		}
		
		if (anaTipologia != null) {
			_hashCode = 29 * _hashCode + anaTipologia.hashCode();
		}
		
		if (anaAggDt != null) {
			_hashCode = 29 * _hashCode + anaAggDt.hashCode();
		}
		
		if (anaCfPiva != null) {
			_hashCode = 29 * _hashCode + anaCfPiva.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return AnagraficaPk
	 */
	public AnagraficaPk createPk()
	{
		return new AnagraficaPk(anaId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.Anagrafica: " );
		ret.append( "anaId=" + anaId );
		ret.append( ", anaRagioneSociale=" + anaRagioneSociale );
		ret.append( ", anaTipologia=" + anaTipologia );
		ret.append( ", anaAggDt=" + anaAggDt );
		ret.append( ", anaCfPiva=" + anaCfPiva );
		return ret.toString();
	}

}
