/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the corrieri table.
 */
public class CorrieriPk implements Serializable
{
	protected long corId;

	/** 
	 * This attribute represents whether the primitive attribute corId is null.
	 */
	protected boolean corIdNull;

	/** 
	 * Sets the value of corId
	 */
	public void setCorId(long corId)
	{
		this.corId = corId;
	}

	/** 
	 * Gets the value of corId
	 */
	public long getCorId()
	{
		return corId;
	}

	/**
	 * Method 'CorrieriPk'
	 * 
	 */
	public CorrieriPk()
	{
	}

	/**
	 * Method 'CorrieriPk'
	 * 
	 * @param corId
	 */
	public CorrieriPk(final long corId)
	{
		this.corId = corId;
	}

	/** 
	 * Sets the value of corIdNull
	 */
	public void setCorIdNull(boolean corIdNull)
	{
		this.corIdNull = corIdNull;
	}

	/** 
	 * Gets the value of corIdNull
	 */
	public boolean isCorIdNull()
	{
		return corIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CorrieriPk)) {
			return false;
		}
		
		final CorrieriPk _cast = (CorrieriPk) _other;
		if (corId != _cast.corId) {
			return false;
		}
		
		if (corIdNull != _cast.corIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (corId ^ (corId >>> 32));
		_hashCode = 29 * _hashCode + (corIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.CorrieriPk: " );
		ret.append( "corId=" + corId );
		return ret.toString();
	}

}
