/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the movimentazioni_articoli table.
 */
public class MovimentazioniArticoliPk implements Serializable
{
	protected long mvdId;

	/** 
	 * This attribute represents whether the primitive attribute mvdId is null.
	 */
	protected boolean mvdIdNull;

	/** 
	 * Sets the value of mvdId
	 */
	public void setMvdId(long mvdId)
	{
		this.mvdId = mvdId;
	}

	/** 
	 * Gets the value of mvdId
	 */
	public long getMvdId()
	{
		return mvdId;
	}

	/**
	 * Method 'MovimentazioniArticoliPk'
	 * 
	 */
	public MovimentazioniArticoliPk()
	{
	}

	/**
	 * Method 'MovimentazioniArticoliPk'
	 * 
	 * @param mvdId
	 */
	public MovimentazioniArticoliPk(final long mvdId)
	{
		this.mvdId = mvdId;
	}

	/** 
	 * Sets the value of mvdIdNull
	 */
	public void setMvdIdNull(boolean mvdIdNull)
	{
		this.mvdIdNull = mvdIdNull;
	}

	/** 
	 * Gets the value of mvdIdNull
	 */
	public boolean isMvdIdNull()
	{
		return mvdIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MovimentazioniArticoliPk)) {
			return false;
		}
		
		final MovimentazioniArticoliPk _cast = (MovimentazioniArticoliPk) _other;
		if (mvdId != _cast.mvdId) {
			return false;
		}
		
		if (mvdIdNull != _cast.mvdIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (mvdId ^ (mvdId >>> 32));
		_hashCode = 29 * _hashCode + (mvdIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.MovimentazioniArticoliPk: " );
		ret.append( "mvdId=" + mvdId );
		return ret.toString();
	}

}
