/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the movimentazioni table.
 */
public class MovimentazioniPk implements Serializable
{
	protected long movId;

	/** 
	 * This attribute represents whether the primitive attribute movId is null.
	 */
	protected boolean movIdNull;

	/** 
	 * Sets the value of movId
	 */
	public void setMovId(long movId)
	{
		this.movId = movId;
	}

	/** 
	 * Gets the value of movId
	 */
	public long getMovId()
	{
		return movId;
	}

	/**
	 * Method 'MovimentazioniPk'
	 * 
	 */
	public MovimentazioniPk()
	{
	}

	/**
	 * Method 'MovimentazioniPk'
	 * 
	 * @param movId
	 */
	public MovimentazioniPk(final long movId)
	{
		this.movId = movId;
	}

	/** 
	 * Sets the value of movIdNull
	 */
	public void setMovIdNull(boolean movIdNull)
	{
		this.movIdNull = movIdNull;
	}

	/** 
	 * Gets the value of movIdNull
	 */
	public boolean isMovIdNull()
	{
		return movIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MovimentazioniPk)) {
			return false;
		}
		
		final MovimentazioniPk _cast = (MovimentazioniPk) _other;
		if (movId != _cast.movId) {
			return false;
		}
		
		if (movIdNull != _cast.movIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (movId ^ (movId >>> 32));
		_hashCode = 29 * _hashCode + (movIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.MovimentazioniPk: " );
		ret.append( "movId=" + movId );
		return ret.toString();
	}

}
