/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import com.inn.logistica.dao.*;
import com.inn.logistica.factory.*;
import com.inn.logistica.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Ordini implements Serializable
{
	/** 
	 * This attribute maps to the column ord_id in the ordini table.
	 */
	protected long ordId;

	/** 
	 * This attribute maps to the column ord_data in the ordini table.
	 */
	protected Date ordData;

	/** 
	 * This attribute maps to the column ord_numero in the ordini table.
	 */
	protected String ordNumero;

	/** 
	 * This attribute maps to the column ord_sped_data in the ordini table.
	 */
	protected Date ordSpedData;

	/** 
	 * This attribute maps to the column ord_spe_numero in the ordini table.
	 */
	protected String ordSpeNumero;

	/** 
	 * This attribute maps to the column ord_stato in the ordini table.
	 */
	protected String ordStato;

	/** 
	 * This attribute maps to the column anagrafica_ana_id in the ordini table.
	 */
	protected long anagraficaAnaId;

	/** 
	 * This attribute maps to the column corrieri_cor_id in the ordini table.
	 */
	protected long corrieriCorId;

	/** 
	 * This attribute represents whether the primitive attribute corrieriCorId is null.
	 */
	protected boolean corrieriCorIdNull = true;

	/** 
	 * This attribute maps to the column ord_consegnato in the ordini table.
	 */
	protected Date ordConsegnato;

	/**
	 * Method 'Ordini'
	 * 
	 */
	public Ordini()
	{
	}

	/**
	 * Method 'getOrdId'
	 * 
	 * @return long
	 */
	public long getOrdId()
	{
		return ordId;
	}

	/**
	 * Method 'setOrdId'
	 * 
	 * @param ordId
	 */
	public void setOrdId(long ordId)
	{
		this.ordId = ordId;
	}

	/**
	 * Method 'getOrdData'
	 * 
	 * @return Date
	 */
	public Date getOrdData()
	{
		return ordData;
	}

	/**
	 * Method 'setOrdData'
	 * 
	 * @param ordData
	 */
	public void setOrdData(Date ordData)
	{
		this.ordData = ordData;
	}

	/**
	 * Method 'getOrdNumero'
	 * 
	 * @return String
	 */
	public String getOrdNumero()
	{
		return ordNumero;
	}

	/**
	 * Method 'setOrdNumero'
	 * 
	 * @param ordNumero
	 */
	public void setOrdNumero(String ordNumero)
	{
		this.ordNumero = ordNumero;
	}

	/**
	 * Method 'getOrdSpedData'
	 * 
	 * @return Date
	 */
	public Date getOrdSpedData()
	{
		return ordSpedData;
	}

	/**
	 * Method 'setOrdSpedData'
	 * 
	 * @param ordSpedData
	 */
	public void setOrdSpedData(Date ordSpedData)
	{
		this.ordSpedData = ordSpedData;
	}

	/**
	 * Method 'getOrdSpeNumero'
	 * 
	 * @return String
	 */
	public String getOrdSpeNumero()
	{
		return ordSpeNumero;
	}

	/**
	 * Method 'setOrdSpeNumero'
	 * 
	 * @param ordSpeNumero
	 */
	public void setOrdSpeNumero(String ordSpeNumero)
	{
		this.ordSpeNumero = ordSpeNumero;
	}

	/**
	 * Method 'getOrdStato'
	 * 
	 * @return String
	 */
	public String getOrdStato()
	{
		return ordStato;
	}

	/**
	 * Method 'setOrdStato'
	 * 
	 * @param ordStato
	 */
	public void setOrdStato(String ordStato)
	{
		this.ordStato = ordStato;
	}

	/**
	 * Method 'getAnagraficaAnaId'
	 * 
	 * @return long
	 */
	public long getAnagraficaAnaId()
	{
		return anagraficaAnaId;
	}

	/**
	 * Method 'setAnagraficaAnaId'
	 * 
	 * @param anagraficaAnaId
	 */
	public void setAnagraficaAnaId(long anagraficaAnaId)
	{
		this.anagraficaAnaId = anagraficaAnaId;
	}

	/**
	 * Method 'getCorrieriCorId'
	 * 
	 * @return long
	 */
	public long getCorrieriCorId()
	{
		return corrieriCorId;
	}

	/**
	 * Method 'setCorrieriCorId'
	 * 
	 * @param corrieriCorId
	 */
	public void setCorrieriCorId(long corrieriCorId)
	{
		this.corrieriCorId = corrieriCorId;
		this.corrieriCorIdNull = false;
	}

	/**
	 * Method 'setCorrieriCorIdNull'
	 * 
	 * @param value
	 */
	public void setCorrieriCorIdNull(boolean value)
	{
		this.corrieriCorIdNull = value;
	}

	/**
	 * Method 'isCorrieriCorIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isCorrieriCorIdNull()
	{
		return corrieriCorIdNull;
	}

	/**
	 * Method 'getOrdConsegnato'
	 * 
	 * @return Date
	 */
	public Date getOrdConsegnato()
	{
		return ordConsegnato;
	}

	/**
	 * Method 'setOrdConsegnato'
	 * 
	 * @param ordConsegnato
	 */
	public void setOrdConsegnato(Date ordConsegnato)
	{
		this.ordConsegnato = ordConsegnato;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Ordini)) {
			return false;
		}
		
		final Ordini _cast = (Ordini) _other;
		if (ordId != _cast.ordId) {
			return false;
		}
		
		if (ordData == null ? _cast.ordData != ordData : !ordData.equals( _cast.ordData )) {
			return false;
		}
		
		if (ordNumero == null ? _cast.ordNumero != ordNumero : !ordNumero.equals( _cast.ordNumero )) {
			return false;
		}
		
		if (ordSpedData == null ? _cast.ordSpedData != ordSpedData : !ordSpedData.equals( _cast.ordSpedData )) {
			return false;
		}
		
		if (ordSpeNumero == null ? _cast.ordSpeNumero != ordSpeNumero : !ordSpeNumero.equals( _cast.ordSpeNumero )) {
			return false;
		}
		
		if (ordStato == null ? _cast.ordStato != ordStato : !ordStato.equals( _cast.ordStato )) {
			return false;
		}
		
		if (anagraficaAnaId != _cast.anagraficaAnaId) {
			return false;
		}
		
		if (corrieriCorId != _cast.corrieriCorId) {
			return false;
		}
		
		if (corrieriCorIdNull != _cast.corrieriCorIdNull) {
			return false;
		}
		
		if (ordConsegnato == null ? _cast.ordConsegnato != ordConsegnato : !ordConsegnato.equals( _cast.ordConsegnato )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (ordId ^ (ordId >>> 32));
		if (ordData != null) {
			_hashCode = 29 * _hashCode + ordData.hashCode();
		}
		
		if (ordNumero != null) {
			_hashCode = 29 * _hashCode + ordNumero.hashCode();
		}
		
		if (ordSpedData != null) {
			_hashCode = 29 * _hashCode + ordSpedData.hashCode();
		}
		
		if (ordSpeNumero != null) {
			_hashCode = 29 * _hashCode + ordSpeNumero.hashCode();
		}
		
		if (ordStato != null) {
			_hashCode = 29 * _hashCode + ordStato.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (anagraficaAnaId ^ (anagraficaAnaId >>> 32));
		_hashCode = 29 * _hashCode + (int) (corrieriCorId ^ (corrieriCorId >>> 32));
		_hashCode = 29 * _hashCode + (corrieriCorIdNull ? 1 : 0);
		if (ordConsegnato != null) {
			_hashCode = 29 * _hashCode + ordConsegnato.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return OrdiniPk
	 */
	public OrdiniPk createPk()
	{
		return new OrdiniPk(ordId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.Ordini: " );
		ret.append( "ordId=" + ordId );
		ret.append( ", ordData=" + ordData );
		ret.append( ", ordNumero=" + ordNumero );
		ret.append( ", ordSpedData=" + ordSpedData );
		ret.append( ", ordSpeNumero=" + ordSpeNumero );
		ret.append( ", ordStato=" + ordStato );
		ret.append( ", anagraficaAnaId=" + anagraficaAnaId );
		ret.append( ", corrieriCorId=" + corrieriCorId );
		ret.append( ", ordConsegnato=" + ordConsegnato );
		return ret.toString();
	}

}
