/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the utente table.
 */
public class UtentePk implements Serializable
{
	protected long uteId;

	/** 
	 * This attribute represents whether the primitive attribute uteId is null.
	 */
	protected boolean uteIdNull;

	/** 
	 * Sets the value of uteId
	 */
	public void setUteId(long uteId)
	{
		this.uteId = uteId;
	}

	/** 
	 * Gets the value of uteId
	 */
	public long getUteId()
	{
		return uteId;
	}

	/**
	 * Method 'UtentePk'
	 * 
	 */
	public UtentePk()
	{
	}

	/**
	 * Method 'UtentePk'
	 * 
	 * @param uteId
	 */
	public UtentePk(final long uteId)
	{
		this.uteId = uteId;
	}

	/** 
	 * Sets the value of uteIdNull
	 */
	public void setUteIdNull(boolean uteIdNull)
	{
		this.uteIdNull = uteIdNull;
	}

	/** 
	 * Gets the value of uteIdNull
	 */
	public boolean isUteIdNull()
	{
		return uteIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof UtentePk)) {
			return false;
		}
		
		final UtentePk _cast = (UtentePk) _other;
		if (uteId != _cast.uteId) {
			return false;
		}
		
		if (uteIdNull != _cast.uteIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (uteId ^ (uteId >>> 32));
		_hashCode = 29 * _hashCode + (uteIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.UtentePk: " );
		ret.append( "uteId=" + uteId );
		return ret.toString();
	}

}
