/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.exceptions;

public class MovimentazioniDaoException extends DaoException
{
	/**
	 * Method 'MovimentazioniDaoException'
	 * 
	 * @param message
	 */
	public MovimentazioniDaoException(String message)
	{
		super(message);
	}

	/**
	 * Method 'MovimentazioniDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public MovimentazioniDaoException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
