/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.inn.logistica.dao.AnagraficaDao;
import com.inn.logistica.dto.Anagrafica;
import com.inn.logistica.exceptions.AnagraficaDaoException;
import com.inn.logistica.factory.AnagraficaDaoFactory;

public class AnagraficaDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereAnaIdEquals(0);
		// findWhereAnaRagioneSocialeEquals("");
		// findWhereAnaTipologiaEquals("");
		// findWhereAnaAggDtEquals(null);
		// findWhereAnaCfPivaEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			AnagraficaDao _dao = getAnagraficaDao();
			Anagrafica _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAnaIdEquals'
	 * 
	 * @param anaId
	 */
	public static void findWhereAnaIdEquals(long anaId)
	{
		try {
			AnagraficaDao _dao = getAnagraficaDao();
			Anagrafica _result[] = _dao.findWhereAnaIdEquals(anaId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAnaRagioneSocialeEquals'
	 * 
	 * @param anaRagioneSociale
	 */
	public static void findWhereAnaRagioneSocialeEquals(String anaRagioneSociale)
	{
		try {
			AnagraficaDao _dao = getAnagraficaDao();
			Anagrafica _result[] = _dao.findWhereAnaRagioneSocialeEquals(anaRagioneSociale);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAnaTipologiaEquals'
	 * 
	 * @param anaTipologia
	 */
	public static void findWhereAnaTipologiaEquals(String anaTipologia)
	{
		try {
			AnagraficaDao _dao = getAnagraficaDao();
			Anagrafica _result[] = _dao.findWhereAnaTipologiaEquals(anaTipologia);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAnaAggDtEquals'
	 * 
	 * @param anaAggDt
	 */
	public static void findWhereAnaAggDtEquals(Date anaAggDt)
	{
		try {
			AnagraficaDao _dao = getAnagraficaDao();
			Anagrafica _result[] = _dao.findWhereAnaAggDtEquals(anaAggDt);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAnaCfPivaEquals'
	 * 
	 * @param anaCfPiva
	 */
	public static void findWhereAnaCfPivaEquals(String anaCfPiva)
	{
		try {
			AnagraficaDao _dao = getAnagraficaDao();
			Anagrafica _result[] = _dao.findWhereAnaCfPivaEquals(anaCfPiva);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getAnagraficaDao'
	 * 
	 * @return AnagraficaDao
	 */
	public static AnagraficaDao getAnagraficaDao()
	{
		return AnagraficaDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Anagrafica dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getAnaId() );
		buf.append( ", " );
		buf.append( dto.getAnaRagioneSociale() );
		buf.append( ", " );
		buf.append( dto.getAnaTipologia() );
		buf.append( ", " );
		buf.append( dto.getAnaAggDt() );
		buf.append( ", " );
		buf.append( dto.getAnaCfPiva() );
		System.out.println( buf.toString() );
	}

}
