/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.inn.logistica.dao.ArticoloDao;
import com.inn.logistica.dto.Articolo;
import com.inn.logistica.exceptions.ArticoloDaoException;
import com.inn.logistica.factory.ArticoloDaoFactory;

public class ArticoloDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereArtIdEquals(0);
		// findWhereArtCodiceEquals("");
		// findWhereArtDescrizioneEquals("");
		// findWhereArtBarcodeEquals("");
		// findWhereArtGiacenzaEquals(0);
		// findWhereArtAggDtEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ArticoloDao _dao = getArticoloDao();
			Articolo _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereArtIdEquals'
	 * 
	 * @param artId
	 */
	public static void findWhereArtIdEquals(long artId)
	{
		try {
			ArticoloDao _dao = getArticoloDao();
			Articolo _result[] = _dao.findWhereArtIdEquals(artId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereArtCodiceEquals'
	 * 
	 * @param artCodice
	 */
	public static void findWhereArtCodiceEquals(String artCodice)
	{
		try {
			ArticoloDao _dao = getArticoloDao();
			Articolo _result[] = _dao.findWhereArtCodiceEquals(artCodice);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereArtDescrizioneEquals'
	 * 
	 * @param artDescrizione
	 */
	public static void findWhereArtDescrizioneEquals(String artDescrizione)
	{
		try {
			ArticoloDao _dao = getArticoloDao();
			Articolo _result[] = _dao.findWhereArtDescrizioneEquals(artDescrizione);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereArtBarcodeEquals'
	 * 
	 * @param artBarcode
	 */
	public static void findWhereArtBarcodeEquals(String artBarcode)
	{
		try {
			ArticoloDao _dao = getArticoloDao();
			Articolo _result[] = _dao.findWhereArtBarcodeEquals(artBarcode);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereArtGiacenzaEquals'
	 * 
	 * @param artGiacenza
	 */
	public static void findWhereArtGiacenzaEquals(int artGiacenza)
	{
		try {
			ArticoloDao _dao = getArticoloDao();
			Articolo _result[] = _dao.findWhereArtGiacenzaEquals(artGiacenza);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereArtAggDtEquals'
	 * 
	 * @param artAggDt
	 */
	public static void findWhereArtAggDtEquals(Date artAggDt)
	{
		try {
			ArticoloDao _dao = getArticoloDao();
			Articolo _result[] = _dao.findWhereArtAggDtEquals(artAggDt);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getArticoloDao'
	 * 
	 * @return ArticoloDao
	 */
	public static ArticoloDao getArticoloDao()
	{
		return ArticoloDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Articolo dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getArtId() );
		buf.append( ", " );
		buf.append( dto.getArtCodice() );
		buf.append( ", " );
		buf.append( dto.getArtDescrizione() );
		buf.append( ", " );
		buf.append( dto.getArtBarcode() );
		buf.append( ", " );
		buf.append( dto.getArtGiacenza() );
		buf.append( ", " );
		buf.append( dto.getArtAggDt() );
		System.out.println( buf.toString() );
	}

}
