/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.inn.logistica.dao.CorrieriDao;
import com.inn.logistica.dto.Corrieri;
import com.inn.logistica.exceptions.CorrieriDaoException;
import com.inn.logistica.factory.CorrieriDaoFactory;

public class CorrieriDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereCorIdEquals(0);
		// findWhereCorNominativoEquals("");
		// findWhereCorUrlTrackingEquals("");
		// findWhereCorAbilTrackingEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			CorrieriDao _dao = getCorrieriDao();
			Corrieri _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCorIdEquals'
	 * 
	 * @param corId
	 */
	public static void findWhereCorIdEquals(long corId)
	{
		try {
			CorrieriDao _dao = getCorrieriDao();
			Corrieri _result[] = _dao.findWhereCorIdEquals(corId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCorNominativoEquals'
	 * 
	 * @param corNominativo
	 */
	public static void findWhereCorNominativoEquals(String corNominativo)
	{
		try {
			CorrieriDao _dao = getCorrieriDao();
			Corrieri _result[] = _dao.findWhereCorNominativoEquals(corNominativo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCorUrlTrackingEquals'
	 * 
	 * @param corUrlTracking
	 */
	public static void findWhereCorUrlTrackingEquals(String corUrlTracking)
	{
		try {
			CorrieriDao _dao = getCorrieriDao();
			Corrieri _result[] = _dao.findWhereCorUrlTrackingEquals(corUrlTracking);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCorAbilTrackingEquals'
	 * 
	 * @param corAbilTracking
	 */
	public static void findWhereCorAbilTrackingEquals(int corAbilTracking)
	{
		try {
			CorrieriDao _dao = getCorrieriDao();
			Corrieri _result[] = _dao.findWhereCorAbilTrackingEquals(corAbilTracking);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getCorrieriDao'
	 * 
	 * @return CorrieriDao
	 */
	public static CorrieriDao getCorrieriDao()
	{
		return CorrieriDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Corrieri dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getCorId() );
		buf.append( ", " );
		buf.append( dto.getCorNominativo() );
		buf.append( ", " );
		buf.append( dto.getCorUrlTracking() );
		buf.append( ", " );
		buf.append( dto.getCorAbilTracking() );
		System.out.println( buf.toString() );
	}

}
