/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.inn.logistica.dao.MovimentazioniArticoliDao;
import com.inn.logistica.dto.MovimentazioniArticoli;
import com.inn.logistica.exceptions.MovimentazioniArticoliDaoException;
import com.inn.logistica.factory.MovimentazioniArticoliDaoFactory;

public class MovimentazioniArticoliDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByArticolo(0);
		// findByMovimentazioni(0);
		// findWhereMvdIdEquals(0);
		// findWhereMvdQtaEquals(0);
		// findWhereArticoloArtIdEquals(0);
		// findWhereMovimentazioniMovIdEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			MovimentazioniArticoliDao _dao = getMovimentazioniArticoliDao();
			MovimentazioniArticoli _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByArticolo'
	 * 
	 * @param articoloArtId
	 */
	public static void findByArticolo(long articoloArtId)
	{
		try {
			MovimentazioniArticoliDao _dao = getMovimentazioniArticoliDao();
			MovimentazioniArticoli _result[] = _dao.findByArticolo(articoloArtId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByMovimentazioni'
	 * 
	 * @param movimentazioniMovId
	 */
	public static void findByMovimentazioni(long movimentazioniMovId)
	{
		try {
			MovimentazioniArticoliDao _dao = getMovimentazioniArticoliDao();
			MovimentazioniArticoli _result[] = _dao.findByMovimentazioni(movimentazioniMovId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereMvdIdEquals'
	 * 
	 * @param mvdId
	 */
	public static void findWhereMvdIdEquals(long mvdId)
	{
		try {
			MovimentazioniArticoliDao _dao = getMovimentazioniArticoliDao();
			MovimentazioniArticoli _result[] = _dao.findWhereMvdIdEquals(mvdId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereMvdQtaEquals'
	 * 
	 * @param mvdQta
	 */
	public static void findWhereMvdQtaEquals(int mvdQta)
	{
		try {
			MovimentazioniArticoliDao _dao = getMovimentazioniArticoliDao();
			MovimentazioniArticoli _result[] = _dao.findWhereMvdQtaEquals(mvdQta);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereArticoloArtIdEquals'
	 * 
	 * @param articoloArtId
	 */
	public static void findWhereArticoloArtIdEquals(long articoloArtId)
	{
		try {
			MovimentazioniArticoliDao _dao = getMovimentazioniArticoliDao();
			MovimentazioniArticoli _result[] = _dao.findWhereArticoloArtIdEquals(articoloArtId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereMovimentazioniMovIdEquals'
	 * 
	 * @param movimentazioniMovId
	 */
	public static void findWhereMovimentazioniMovIdEquals(long movimentazioniMovId)
	{
		try {
			MovimentazioniArticoliDao _dao = getMovimentazioniArticoliDao();
			MovimentazioniArticoli _result[] = _dao.findWhereMovimentazioniMovIdEquals(movimentazioniMovId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getMovimentazioniArticoliDao'
	 * 
	 * @return MovimentazioniArticoliDao
	 */
	public static MovimentazioniArticoliDao getMovimentazioniArticoliDao()
	{
		return MovimentazioniArticoliDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(MovimentazioniArticoli dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getMvdId() );
		buf.append( ", " );
		buf.append( dto.getMvdQta() );
		buf.append( ", " );
		buf.append( dto.getArticoloArtId() );
		buf.append( ", " );
		buf.append( dto.getMovimentazioniMovId() );
		System.out.println( buf.toString() );
	}

}
