/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.inn.logistica.dao.OrdiniDao;
import com.inn.logistica.dto.Ordini;
import com.inn.logistica.exceptions.OrdiniDaoException;
import com.inn.logistica.factory.OrdiniDaoFactory;

public class OrdiniDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByAnagrafica(0);
		// findByCorrieri(0);
		// findWhereOrdIdEquals(0);
		// findWhereOrdDataEquals(null);
		// findWhereOrdNumeroEquals("");
		// findWhereOrdSpedDataEquals(null);
		// findWhereOrdSpeNumeroEquals("");
		// findWhereOrdStatoEquals("");
		// findWhereAnagraficaAnaIdEquals(0);
		// findWhereCorrieriCorIdEquals(0);
		// findWhereOrdConsegnatoEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			OrdiniDao _dao = getOrdiniDao();
			Ordini _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByAnagrafica'
	 * 
	 * @param anagraficaAnaId
	 */
	public static void findByAnagrafica(long anagraficaAnaId)
	{
		try {
			OrdiniDao _dao = getOrdiniDao();
			Ordini _result[] = _dao.findByAnagrafica(anagraficaAnaId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByCorrieri'
	 * 
	 * @param corrieriCorId
	 */
	public static void findByCorrieri(long corrieriCorId)
	{
		try {
			OrdiniDao _dao = getOrdiniDao();
			Ordini _result[] = _dao.findByCorrieri(corrieriCorId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereOrdIdEquals'
	 * 
	 * @param ordId
	 */
	public static void findWhereOrdIdEquals(long ordId)
	{
		try {
			OrdiniDao _dao = getOrdiniDao();
			Ordini _result[] = _dao.findWhereOrdIdEquals(ordId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereOrdDataEquals'
	 * 
	 * @param ordData
	 */
	public static void findWhereOrdDataEquals(Date ordData)
	{
		try {
			OrdiniDao _dao = getOrdiniDao();
			Ordini _result[] = _dao.findWhereOrdDataEquals(ordData);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereOrdNumeroEquals'
	 * 
	 * @param ordNumero
	 */
	public static void findWhereOrdNumeroEquals(String ordNumero)
	{
		try {
			OrdiniDao _dao = getOrdiniDao();
			Ordini _result[] = _dao.findWhereOrdNumeroEquals(ordNumero);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereOrdSpedDataEquals'
	 * 
	 * @param ordSpedData
	 */
	public static void findWhereOrdSpedDataEquals(Date ordSpedData)
	{
		try {
			OrdiniDao _dao = getOrdiniDao();
			Ordini _result[] = _dao.findWhereOrdSpedDataEquals(ordSpedData);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereOrdSpeNumeroEquals'
	 * 
	 * @param ordSpeNumero
	 */
	public static void findWhereOrdSpeNumeroEquals(String ordSpeNumero)
	{
		try {
			OrdiniDao _dao = getOrdiniDao();
			Ordini _result[] = _dao.findWhereOrdSpeNumeroEquals(ordSpeNumero);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereOrdStatoEquals'
	 * 
	 * @param ordStato
	 */
	public static void findWhereOrdStatoEquals(String ordStato)
	{
		try {
			OrdiniDao _dao = getOrdiniDao();
			Ordini _result[] = _dao.findWhereOrdStatoEquals(ordStato);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAnagraficaAnaIdEquals'
	 * 
	 * @param anagraficaAnaId
	 */
	public static void findWhereAnagraficaAnaIdEquals(long anagraficaAnaId)
	{
		try {
			OrdiniDao _dao = getOrdiniDao();
			Ordini _result[] = _dao.findWhereAnagraficaAnaIdEquals(anagraficaAnaId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCorrieriCorIdEquals'
	 * 
	 * @param corrieriCorId
	 */
	public static void findWhereCorrieriCorIdEquals(long corrieriCorId)
	{
		try {
			OrdiniDao _dao = getOrdiniDao();
			Ordini _result[] = _dao.findWhereCorrieriCorIdEquals(corrieriCorId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereOrdConsegnatoEquals'
	 * 
	 * @param ordConsegnato
	 */
	public static void findWhereOrdConsegnatoEquals(Date ordConsegnato)
	{
		try {
			OrdiniDao _dao = getOrdiniDao();
			Ordini _result[] = _dao.findWhereOrdConsegnatoEquals(ordConsegnato);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getOrdiniDao'
	 * 
	 * @return OrdiniDao
	 */
	public static OrdiniDao getOrdiniDao()
	{
		return OrdiniDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Ordini dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getOrdId() );
		buf.append( ", " );
		buf.append( dto.getOrdData() );
		buf.append( ", " );
		buf.append( dto.getOrdNumero() );
		buf.append( ", " );
		buf.append( dto.getOrdSpedData() );
		buf.append( ", " );
		buf.append( dto.getOrdSpeNumero() );
		buf.append( ", " );
		buf.append( dto.getOrdStato() );
		buf.append( ", " );
		buf.append( dto.getAnagraficaAnaId() );
		buf.append( ", " );
		buf.append( dto.getCorrieriCorId() );
		buf.append( ", " );
		buf.append( dto.getOrdConsegnato() );
		System.out.println( buf.toString() );
	}

}
