/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.inn.logistica.dao.UtenteDao;
import com.inn.logistica.dto.Utente;
import com.inn.logistica.exceptions.UtenteDaoException;
import com.inn.logistica.factory.UtenteDaoFactory;

public class UtenteDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereUteIdEquals(0);
		// findWhereUteNominativoEquals("");
		// findWhereUteEmailEquals("");
		// findWhereUtePasswordEquals("");
		// findWhereUteCfPivaEquals("");
		// findWhereUteProfiloEquals("");
		// findWhereUteStatoEquals("");
		// findWhereUteLastLoginEquals(null);
		// findWhereUteTentativiEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			UtenteDao _dao = getUtenteDao();
			Utente _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUteIdEquals'
	 * 
	 * @param uteId
	 */
	public static void findWhereUteIdEquals(long uteId)
	{
		try {
			UtenteDao _dao = getUtenteDao();
			Utente _result[] = _dao.findWhereUteIdEquals(uteId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUteNominativoEquals'
	 * 
	 * @param uteNominativo
	 */
	public static void findWhereUteNominativoEquals(String uteNominativo)
	{
		try {
			UtenteDao _dao = getUtenteDao();
			Utente _result[] = _dao.findWhereUteNominativoEquals(uteNominativo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUteEmailEquals'
	 * 
	 * @param uteEmail
	 */
	public static void findWhereUteEmailEquals(String uteEmail)
	{
		try {
			UtenteDao _dao = getUtenteDao();
			Utente _result[] = _dao.findWhereUteEmailEquals(uteEmail);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUtePasswordEquals'
	 * 
	 * @param utePassword
	 */
	public static void findWhereUtePasswordEquals(String utePassword)
	{
		try {
			UtenteDao _dao = getUtenteDao();
			Utente _result[] = _dao.findWhereUtePasswordEquals(utePassword);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUteCfPivaEquals'
	 * 
	 * @param uteCfPiva
	 */
	public static void findWhereUteCfPivaEquals(String uteCfPiva)
	{
		try {
			UtenteDao _dao = getUtenteDao();
			Utente _result[] = _dao.findWhereUteCfPivaEquals(uteCfPiva);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUteProfiloEquals'
	 * 
	 * @param uteProfilo
	 */
	public static void findWhereUteProfiloEquals(String uteProfilo)
	{
		try {
			UtenteDao _dao = getUtenteDao();
			Utente _result[] = _dao.findWhereUteProfiloEquals(uteProfilo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUteStatoEquals'
	 * 
	 * @param uteStato
	 */
	public static void findWhereUteStatoEquals(String uteStato)
	{
		try {
			UtenteDao _dao = getUtenteDao();
			Utente _result[] = _dao.findWhereUteStatoEquals(uteStato);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUteLastLoginEquals'
	 * 
	 * @param uteLastLogin
	 */
	public static void findWhereUteLastLoginEquals(Date uteLastLogin)
	{
		try {
			UtenteDao _dao = getUtenteDao();
			Utente _result[] = _dao.findWhereUteLastLoginEquals(uteLastLogin);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUteTentativiEquals'
	 * 
	 * @param uteTentativi
	 */
	public static void findWhereUteTentativiEquals(int uteTentativi)
	{
		try {
			UtenteDao _dao = getUtenteDao();
			Utente _result[] = _dao.findWhereUteTentativiEquals(uteTentativi);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getUtenteDao'
	 * 
	 * @return UtenteDao
	 */
	public static UtenteDao getUtenteDao()
	{
		return UtenteDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Utente dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getUteId() );
		buf.append( ", " );
		buf.append( dto.getUteNominativo() );
		buf.append( ", " );
		buf.append( dto.getUteEmail() );
		buf.append( ", " );
		buf.append( dto.getUtePassword() );
		buf.append( ", " );
		buf.append( dto.getUteCfPiva() );
		buf.append( ", " );
		buf.append( dto.getUteProfilo() );
		buf.append( ", " );
		buf.append( dto.getUteStato() );
		buf.append( ", " );
		buf.append( dto.getUteLastLogin() );
		buf.append( ", " );
		buf.append( dto.getUteTentativi() );
		System.out.println( buf.toString() );
	}

}
