/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.inn.logistica.dto;

import com.inn.logistica.dao.*;
import com.inn.logistica.factory.*;
import com.inn.logistica.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Movimentazioni implements Serializable
{
	/** 
	 * This attribute maps to the column mov_id in the movimentazioni table.
	 */
	protected long movId;

	/** 
	 * This attribute maps to the column mov_data in the movimentazioni table.
	 */
	protected Date movData;

	/** 
	 * This attribute maps to the column mov_ora in the movimentazioni table.
	 */
	protected String movOra;

	/** 
	 * This attribute maps to the column mov_tipo in the movimentazioni table.
	 */
	protected String movTipo;

	/** 
	 * This attribute maps to the column anagrafica_ana_id in the movimentazioni table.
	 */
	protected long anagraficaAnaId;

	/** 
	 * This attribute represents whether the primitive attribute anagraficaAnaId is null.
	 */
	protected boolean anagraficaAnaIdNull = true;

	/**
	 * Method 'Movimentazioni'
	 * 
	 */
	public Movimentazioni()
	{
	}

	/**
	 * Method 'getMovId'
	 * 
	 * @return long
	 */
	public long getMovId()
	{
		return movId;
	}

	/**
	 * Method 'setMovId'
	 * 
	 * @param movId
	 */
	public void setMovId(long movId)
	{
		this.movId = movId;
	}

	/**
	 * Method 'getMovData'
	 * 
	 * @return Date
	 */
	public Date getMovData()
	{
		return movData;
	}

	/**
	 * Method 'setMovData'
	 * 
	 * @param movData
	 */
	public void setMovData(Date movData)
	{
		this.movData = movData;
	}

	/**
	 * Method 'getMovOra'
	 * 
	 * @return String
	 */
	public String getMovOra()
	{
		return movOra;
	}

	/**
	 * Method 'setMovOra'
	 * 
	 * @param movOra
	 */
	public void setMovOra(String movOra)
	{
		this.movOra = movOra;
	}

	/**
	 * Method 'getMovTipo'
	 * 
	 * @return String
	 */
	public String getMovTipo()
	{
		return movTipo;
	}

	/**
	 * Method 'setMovTipo'
	 * 
	 * @param movTipo
	 */
	public void setMovTipo(String movTipo)
	{
		this.movTipo = movTipo;
	}

	/**
	 * Method 'getAnagraficaAnaId'
	 * 
	 * @return long
	 */
	public long getAnagraficaAnaId()
	{
		return anagraficaAnaId;
	}

	/**
	 * Method 'setAnagraficaAnaId'
	 * 
	 * @param anagraficaAnaId
	 */
	public void setAnagraficaAnaId(long anagraficaAnaId)
	{
		this.anagraficaAnaId = anagraficaAnaId;
		this.anagraficaAnaIdNull = false;
	}

	/**
	 * Method 'setAnagraficaAnaIdNull'
	 * 
	 * @param value
	 */
	public void setAnagraficaAnaIdNull(boolean value)
	{
		this.anagraficaAnaIdNull = value;
	}

	/**
	 * Method 'isAnagraficaAnaIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isAnagraficaAnaIdNull()
	{
		return anagraficaAnaIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Movimentazioni)) {
			return false;
		}
		
		final Movimentazioni _cast = (Movimentazioni) _other;
		if (movId != _cast.movId) {
			return false;
		}
		
		if (movData == null ? _cast.movData != movData : !movData.equals( _cast.movData )) {
			return false;
		}
		
		if (movOra == null ? _cast.movOra != movOra : !movOra.equals( _cast.movOra )) {
			return false;
		}
		
		if (movTipo == null ? _cast.movTipo != movTipo : !movTipo.equals( _cast.movTipo )) {
			return false;
		}
		
		if (anagraficaAnaId != _cast.anagraficaAnaId) {
			return false;
		}
		
		if (anagraficaAnaIdNull != _cast.anagraficaAnaIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (movId ^ (movId >>> 32));
		if (movData != null) {
			_hashCode = 29 * _hashCode + movData.hashCode();
		}
		
		if (movOra != null) {
			_hashCode = 29 * _hashCode + movOra.hashCode();
		}
		
		if (movTipo != null) {
			_hashCode = 29 * _hashCode + movTipo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (anagraficaAnaId ^ (anagraficaAnaId >>> 32));
		_hashCode = 29 * _hashCode + (anagraficaAnaIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MovimentazioniPk
	 */
	public MovimentazioniPk createPk()
	{
		return new MovimentazioniPk(movId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.inn.logistica.dto.Movimentazioni: " );
		ret.append( "movId=" + movId );
		ret.append( ", movData=" + movData );
		ret.append( ", movOra=" + movOra );
		ret.append( ", movTipo=" + movTipo );
		ret.append( ", anagraficaAnaId=" + anagraficaAnaId );
		return ret.toString();
	}

}
